# Generated by Django 5.2.1 on 2025-05-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('body', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('develop_lang', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('java', 'Java'), ('ruby', 'Ruby'), ('php', 'PHP'), ('go', 'Go'), ('rust', 'Rust'), ('csharp', 'C#'), ('cpp', 'C++'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('other', 'その他')], default='python', max_length=20, verbose_name='開発言語')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
